config/routes.rb
Rails.application.routes.draw do

  root "artists#index"

  #resources :artists
  resources :songs
  resources :pictures

  resources :artists do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_one :picture, dependent: :destroy

  validates :name, presence: true
  validates :bio, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :title, presence: true, length: {maximum: 30}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController


  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def destroy
    Artist.find(params[:id]).destroy
    redirect_to root_path
  end

  def self.order_by_name
    order(:name)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
before_action :set_artist, only:[:create, :new]

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = @artist.songs.new
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to @artist
    else
      render 'new'
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @artist = @song.artist.id
    @song.destroy
    redirect_to artist_path(@artist)
  end


   private

   def set_artist
     @artist = Artist.find(params[:artist_id])
   end

   def song_params
     params.require(:song).permit(:title, :album, :released, :artist_id)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<header>
    <div>
        <h1>Artist Overview</h1>
    </div>
</header>

<section class="artist-gallery">
    <% @artists.each do |artist| %>
    <article class="artist-card">
        <div class="artist-image">
            <h3><%= link_to artist.name, artist_path(artist.id) %></h3>
        </div>
        <div>
            <%= link_to image_tag(artist.picture.image, size: "250x250"), artist_path(artist.id) %>

            <% end %>
        </div>

    </article>

</section>

app/views/artists/show.html.erb
<section class="body_show">
    <h1><%= @artist.name %></h1>
    <%= image_tag(@artist.picture.image, size: "250x250") %>

    <p>Biography:
        <%= @artist.bio %></p>
    <p>Genre:
        <%= @artist.genre %></p>
    <p>Country:
        <%= @artist.country %></p>
    <p>Record Label:
        <%= @artist.label %></p>

    <h4>List of Songs</h4>

    <% if @artist.songs.any? %>
    <ul>
        <% @artist.songs.each do |song| %>
        <li><%= link_to song.title,
      song_path(song.id) %></li>
        <% end %>
    </ul>
<% else %>
    <p>There are no songs for this artist.</p>
    <% end %>

    <p><%= link_to "Add new song",  new_artist_song_path(@artist, @song), class: "btn btn-default" %></p>
    <p><%= link_to "Delete Artist", artist_path, method: :delete, data: { confirm: 'Are you sure? The Artist and all of it\'s songs will be deleted!' }, class: "btn btn-default" %></p> <p><%= link_to "Back", root_path, class: "btn btn-default" %></p>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for [@artist,@song] do |f| %>

  <% @song.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>
  <div class="form-group">
      <label>Title</label>
      <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
  </div>

  <div class="form-group">
      <label>Release Date: </label>
      <%= f.date_select :released, :start_year => 1950 %>
  </div>

  <div class="form-group">
      <label>Album</label>
      <%= f.text_field :album, placeholder: "Album Title", class: "form-control" %>
  </div>

  <div class="actions">
      <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/songs/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new song
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/songs/show.html.erb
<section class="body_show">
    <h1><%= @song.title %></h1>
    <% if @song.img_url? %>
      <%= image_tag @song.img_url, size: "250x250" %>
    <% end %>
    <p>Album:
        <%= @song.album %></p>

    <% if @song.released %>
    <p>Release date:
        <%= @song.released.strftime("%d-%m-%Y") %></p>
      <% else %>
        <p>Release date: unknown</p>
    <% end %>

    <p><%= link_to "Delete song", song_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></p>
</section>